credentials:
  usernames:
    david:
      email: david.kakanis@hotmail.com
      name: David
      password: verander
    emi:
      email: unknown
      name: Emi
      password: vrouwkind
    rick:
      email: rick.lokman@hva.nl
      name: Rick
      password: wachtwoord
cookie:
  expiry_days: 30
  name: 'transcriptie_app_cookie'
  key: 'een_random_signature_key'
preauthorized:
  emails:
    - 'geautoriseerde_gebruiker@example.com'
