credentials:
  usernames:
    david:
      email: david.kakanis@hotmail.com
      name: David
      password: verander 
cookie:
  expiry_days: 30
  name: 'transcriptie_app_cookie'
  key: 'een_random_signature_key'
preauthorized:
  emails:
    - 'geautoriseerde_gebruiker@example.com'
